# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BiZhi' do
    
    pod 'SDWebImage'
    pod 'MJExtension'
    pod 'MJRefresh'
    
    pod 'BearSkill', :git => 'https://github.com/BearRan/BearSkill.git', :commit => 'd86df28'
    #  pod 'BearSkill', :path => '../BearSkill/'
    
end

